apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
spec:
  encryptedData:
    api-token: AgBD8XlljCag6tuQ9HK239BNRgawq7w4xq/AHCOUojzGLv2pCnWwwJ/O1+tanb7HxEgwOVoEQ0cDt6LFAWmI8CI6lYbM2LL0IbruJQWNL6llZzTLil4yxB+y3WL/wl7dm5oWW9PCIPvPx4i4vxam2Ws8M1N2aRYHRt24wCd5ukNVTlS8LUlqpV5BEQtHH3WoM/4d9o6XCDpMi2bsYHfYZEF1vgfLsxNl3zRqo45RINSURW3YN3tTuLMFuafpUMqUcQnfnlEkz/2YxCWMQ68Tb5qwEE1mhx3tRWunhhQjDz7CymPwNTnO7RAITpW1dOsde45MgPCLteLGiLbEMgzMLKeHW/+Lw1tvhr1ySTW2YFOcTCY9ZOiII52qByIZGhUIPulrsCfy5H43lpvdHoY4VH4VClGhL+9d/OJFjzVXl0UItyv9+l5rWRjkmKsFEZXT0TGVEoLB0VMI3zh2KeMoZX4VYA7LvSbxSCZm/O6nAKWSNP/5hy6ae7tK4a1aGJLAKosHFpdyVSXOtOhSvDQBOiGFd/c3y7254YP0cynZXSpBc7jSrlht40rUG/ByaUKjuiBw5c4K0fg1oreVZFw2kdZZm3T/gfOvDxLW/KyHk16CeoacuksxoFKSXrqUBtbJZ5WNuh7B42Ihoa0vqZ7QrakgfTX7b4eZ/SMo0JbSsdm24SV2arkn5VysomFA5QyS3gfCWNTRQpnoHc8rwu1ASYQEPmn0lFIdSGLUR2tzN4OuLyhBoLNpgfjQ7Q==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret
    type: Opaque
