apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
spec:
  encryptedData:
    api-token: AgAR6S0Og4c1ymHIpQZnaa9rncWf8AzrvrhEtzAsETWrFjPA1JCVy5l1ICohHxuiAtjUJCSKDvuPXWnWgcdpCA6jrnTUPQ1WuuFVIpeUY87kt8LbEMn4caUa4/kuy/zy+u3m1OcHokIDhkXee8Ww6mTNON9N7Tn4OnoDttAUTYpbVA0Be4exnc0gzlynba5zyuwz2HvtBvUYPeLIXOGr5+l/PdGFC3DEnaKOxqDnKtek4EU2PpGf/2Le5rzQTwVhfxK8yabUjU6e6oxfmJBXeGXOjiM5J1WRmNs5D+SWRL9ma/sSMi6PCxdodzsx7sBZlJcU5MikFz8eKawnguTe4KoTXnwNffJMN57X9jEOaNYtoKRIvTELG6QK5z6Tj4Y2+ujsPsclb5uB+twcTsADZ2ZL9I+/MDMHA/fQl6KzLwJQUGpBB8L9Llh2shNq31THavcyPi6QvHs+jGthZhL6bZNE5E+p/3Cf74e6OMLp28ymfAV87pcWfzdlWftym13iE1ivbn6QGmvVHwSjFmejLYtPTkBbcqJGbsBI+FMGieT8FD8lwIicY7CNe/KWmLIgNCGEOIlV/56VneQ3vmevcRCkSBhxN41RhBWmwJRndHGPT50SS8wThZcplJP3lXWCpwbuho45UbnE+HOWJ5Dqqfi8HrG13DSo7FP9YFIEkmNnTlh79W9nRcZ2GDMi/WmyRulFEPrQm3LcW+yEJcQSpShJHJt9FUE4Nu+aZOIPzv9eAdu7oicLPD96
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret
    type: Opaque
