apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
spec:
  encryptedData:
    api-token: AgBOzU6spCF3GZJH6DUNUqmGRs77JylCM/bwN2YNbljnwPDUmo/qJaJqq1nI+NJz/NbcNkkN+otL9brrlvF/bYF0yOf3h+1BAYqhNu/yOccs9l+l0aK1JRDoz2z6rjS4jGfj4jBIcjDmnmGOQ1fKxyERbub+so8N5N/ZwX6B6O6iwW+WmQMJE/IsKIo0TTJJRwHoOoDFOKpBsqQd0RJdztbuVg3qLTzQ4hIa1kg1/p3wGtfchEIR4jj0gFYT0tCyUSryy6CwUUqyYFWw3AuFyy6bLpWnxPH4D7O2E200cvU9iG/a3HASOw6XKB1CIdM9YnkiTgmV5x0kmpTRD2DCbzvmez4d4Lm2zTvKG0/0GDgOqtCLUPV7UOQSIsj3jsGbLsWP6gyIw0fgZrzKH9fgUtEPB+4TxfiD6OlfDlsmOZN3lnUN4hLxNO/3QZg23njL+9dTIh0X0/OWOmV21CQBLxQmx0WFyMedTGLKsFWBtrR6x4JAUjFLsqgxUDaAj+3l081u40IboupnK6BtOSNsI2LVu9cCiumUtBAwHCil2KXlG8nYDQ0BMk7YgURfDc9qd3u/yuRHKDKC+dRjYUxt3ZdGT69aDJA7xLCE/BBJ97SVdBiq+G/7laaJ+0qB1fPv+bhev5/U653bFAKejBw062Ne+A5CQEc/5NsFrSld/+pBPrS33IHrzHIWL0TO8tWld7gqz9Aw0jT7jdHfKwWtXZhd2C4aDjjxrQDKOC0XXwONKd4AAxIU1mKYQA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret
    type: Opaque
