---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.7.4
    chart: sealed-secrets
    helm:
      values: |-
        # https://github.com/argoproj/argo-cd/issues/5991
        commandArgs:
          - "--update-status"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true