apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../base/app

patchesStrategicMerge:
  - deployment.yaml

resources:
- sample-sealed-secret.yaml
- testsealedsecret.yaml
